channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.1.1
  - scikit-learn==1.1.3
  - scipy==1.13.0
name: mlflow-env
